service: docker

provider:
  name: aws
  runtime: nodejs4.3
  region: 'us-east-1'
  stage: 'dev'

plugins:
  - serverless-docker

functions:
  authorizer:
    handler: functions/authorizer.handler
    type: 'TOKEN'
    identitySource: method.request.header.Authorization

  lambdaSuccessProxy:
    handler: functions/index.lambdaProxySuccessHandler
    events:
      - http:
          path: lists
          method: GET
          authorizer:
            name: authorizer
            type: 'TOKEN'
            identitySource: method.request.header.Authorization
      - http:
          path: lists
          method: POST
          authorizer: authorizer
      - http:
          path: lists
          method: PUT

  lambdaErrorProxy:
    handler: functions/index.lambdaProxyErrorHandler
    events:
      - http:
          path: lambda-proxy-error
          method: GET

  lambdaSuccess:
    handler: functions/index.lambdaSuccessHandler
    events:
      - http:
          path: lambda-success
          method: GET
          integration: lambda

  lambdaError:
    handler: functions/index.lambdaErrorHandler
    events:
      - http:
          path: lambda-error
          method: GET
          integration: lambda
